const recipes = [
  {
    title: "Spaghetti Carbonara",
    ingredients: [
      "200g spaghetti",
      "100g pancetta",
      "2 large eggs",
      "50g pecorino cheese",
      "50g parmesan",
      "2 cloves garlic",
      "Salt",
      "Black pepper",
    ],
    nutiritions: {
      calories: 550,
      protein: "22g",
      fat: "24g",
      carbs: "62g",
    },
    instructions: [
      "Bring a large pot of salted water to a boil and cook spaghetti.",
      "Fry pancetta with garlic until crisp.",
      "Beat eggs and mix with cheeses.",
      "Drain pasta and combine with pancetta.",
      "Remove from heat, add egg-cheese mixture, and toss quickly.",
      "Season with salt and pepper, serve immediately.",
    ],
    duration: "25 min",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    title: "Chicken Caesar Salad",
    ingredients: [
      "2 chicken breasts",
      "1 romaine lettuce",
      "50g parmesan",
      "Croutons",
      "Caesar dressing",
      "Olive oil",
      "Salt",
      "Pepper",
    ],
    nutiritions: {
      calories: 420,
      protein: "35g",
      fat: "22g",
      carbs: "18g",
    },
    instructions: [
      "Season and grill chicken breasts, then slice.",
      "Wash and chop lettuce.",
      "Toss lettuce with dressing, add chicken, croutons, and parmesan.",
      "Drizzle with olive oil and serve.",
    ],
    duration: "20 min",
    image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c",
  },
  {
    title: "Vegetable Stir Fry",
    ingredients: [
      "1 bell pepper",
      "1 carrot",
      "100g broccoli",
      "1 onion",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "2 cloves garlic",
      "1 tsp ginger",
    ],
    nutiritions: {
      calories: 180,
      protein: "5g",
      fat: "7g",
      carbs: "26g",
    },
    instructions: [
      "Chop all vegetables into bite-sized pieces.",
      "Heat sesame oil in a wok, add garlic and ginger.",
      "Add vegetables and stir fry for 5-7 minutes.",
      "Add soy sauce, toss, and serve hot.",
    ],
    duration: "15 min",
    image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0",
  },
  {
    title: "Classic Pancakes",
    ingredients: [
      "1 cup flour",
      "2 tbsp sugar",
      "1 tsp baking powder",
      "1/2 tsp salt",
      "1 cup milk",
      "1 egg",
      "2 tbsp melted butter",
    ],
    nutiritions: {
      calories: 210,
      protein: "6g",
      fat: "7g",
      carbs: "30g",
    },
    instructions: [
      "Mix dry ingredients in a bowl.",
      "Whisk milk, egg, and melted butter together.",
      "Combine wet and dry ingredients.",
      "Pour batter onto a hot griddle, cook until bubbles form, flip and cook until golden.",
    ],
    duration: "20 min",
    image: "https://images.unsplash.com/photo-1504674900247-ec6b0b1b7a6b",
  },
  {
    title: "Beef Tacos",
    ingredients: [
      "200g ground beef",
      "1 onion",
      "1 packet taco seasoning",
      "8 taco shells",
      "Lettuce",
      "Tomato",
      "Cheddar cheese",
      "Sour cream",
    ],
    nutiritions: {
      calories: 390,
      protein: "20g",
      fat: "22g",
      carbs: "28g",
    },
    instructions: [
      "Cook ground beef and chopped onion in a skillet.",
      "Add taco seasoning and a little water, simmer.",
      "Fill taco shells with beef, lettuce, tomato, cheese, and sour cream.",
    ],
    duration: "25 min",
    image: "https://images.unsplash.com/photo-1514512364185-4c2b678c5a2a",
  },
  {
    title: "Caprese Salad",
    ingredients: [
      "2 large tomatoes",
      "200g mozzarella",
      "Fresh basil",
      "2 tbsp olive oil",
      "Salt",
      "Black pepper",
    ],
    nutiritions: {
      calories: 250,
      protein: "13g",
      fat: "19g",
      carbs: "7g",
    },
    instructions: [
      "Slice tomatoes and mozzarella.",
      "Arrange on a plate, alternating slices.",
      "Top with basil leaves.",
      "Drizzle with olive oil, season with salt and pepper.",
    ],
    duration: "10 min",
    image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc",
  },
  {
    title: "Miso Soup",
    ingredients: [
      "3 cups dashi stock",
      "2 tbsp miso paste",
      "100g tofu",
      "2 green onions",
      "Wakame seaweed",
    ],
    nutiritions: {
      calories: 90,
      protein: "7g",
      fat: "3g",
      carbs: "8g",
    },
    instructions: [
      "Heat dashi stock in a pot.",
      "Add diced tofu and wakame, simmer for 2 minutes.",
      "Dissolve miso paste in a little hot broth, then add to pot.",
      "Garnish with sliced green onions and serve.",
    ],
    duration: "15 min",
    image: "https://images.unsplash.com/photo-1504674900247-1a781979e8c0",
  },
  {
    title: "Grilled Salmon",
    ingredients: [
      "2 salmon fillets",
      "1 lemon",
      "2 tbsp olive oil",
      "Salt",
      "Black pepper",
      "Fresh dill",
    ],
    nutiritions: {
      calories: 320,
      protein: "28g",
      fat: "22g",
      carbs: "2g",
    },
    instructions: [
      "Preheat grill to medium-high.",
      "Brush salmon with olive oil, season with salt and pepper.",
      "Grill for 4-5 minutes per side.",
      "Serve with lemon wedges and fresh dill.",
    ],
    duration: "20 min",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    title: "Vegetarian Chili",
    ingredients: [
      "1 can kidney beans",
      "1 can black beans",
      "1 can diced tomatoes",
      "1 onion",
      "1 bell pepper",
      "2 cloves garlic",
      "2 tbsp chili powder",
      "1 tsp cumin",
    ],
    nutiritions: {
      calories: 280,
      protein: "12g",
      fat: "3g",
      carbs: "52g",
    },
    instructions: [
      "Sauté onion, bell pepper, and garlic in a pot.",
      "Add beans, tomatoes, and spices.",
      "Simmer for 20 minutes, stirring occasionally.",
      "Serve hot.",
    ],
    duration: "30 min",
    image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c",
  },
  {
    title: "Banana Smoothie",
    ingredients: [
      "2 bananas",
      "1 cup milk",
      "1/2 cup yogurt",
      "1 tbsp honey",
      "Ice cubes",
    ],
    nutiritions: {
      calories: 180,
      protein: "6g",
      fat: "2g",
      carbs: "38g",
    },
    instructions: [
      "Peel and slice bananas.",
      "Add all ingredients to a blender.",
      "Blend until smooth.",
      "Pour into a glass and serve chilled.",
    ],
    duration: "5 min",
    image: "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0",
  },
];

export { recipes };